# fly.toml app configuration file generated for cicdbibtex on 2023-06-08T10:26:48+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "cicdbibtex"
primary_region = "arn"

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
